version: "3.8"

services:

  php:
    image: php:8.2-apache
    container_name: payment_management_php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - app_network

  mysql: 
    image: mysql:8.0
    container_name: payment_management_db
    restart: always
    ports:
      - "3334:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ahmed
      MYSQL_DATABASE: payment_mangement
      MYSQL_USER: ahmed
      MYSQL_PASSWORD: ahmed
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
